name = "HomotopyOpt"
uuid = "8c5e0f79-7402-43d4-9c5c-e1bde87b1895"
authors = ["Matthias Himmelmann <matthias.himmelmann@outlook.de", "Alex Heaton <alexheaton2@gmail.com>"]
version = "0.2.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
ImplicitPlots = "55ecb840-b828-11e9-1645-43f4a9f9ace7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ForwardDiff = "0.10"
HomotopyContinuation = "2.9"
Plots = "1.39"
julia = "^1.9"
